const LIGHT_THEME = {
  background: 'var(--color-white)',
  headerColor: 'var(--color-charcoal)',
  copyColor: 'var(--color-black)',
  linkColor: 'var(--color-black)',
  highlightColor: 'var(--color-gray-400)',
  auxiliaryColor: 'var(--color-charcoal)',
  borderColor: 'var(--color-gray-400)',
  wrapperOverlay: 'rgba(0, 0, 0, 0.1)',
  cardColor: 'var(--color-black)',
  cardOverlay: 'rgba(0, 0, 0, 0.05)',
  cardLinkColor: 'var(--color-blue-600)',
  cardHeaderColor: 'var(--color-black)',
  cardInfoColor: 'var(--color-charcoal)',
  inputColor: 'var(--color-black)',
  inputCaretColor: 'var(--color-gray-600)',
  inputBorderColor: 'var(--color-gray-400)',
  inputLabelColor: 'var(--color-charcoal)',
  inputPlaceholderColor: 'rgba(0, 0, 0, 0.33)',
  inputPlaceholderHover: 'rgba(0, 0, 0, 0.66)',
  inputAutofillColor: 'var(--color-blue-600)',
  cvHeaderColor: 'var(--color-black)',
  cvSubheaderColor: 'var(--color-charcoal)',
  cvInterfaceColor: 'var(--color-charcoal)',
  cvBorderColor: 'var(--color-black)',
  blogSyntaxColor: 'var(--color-gray-600)',
  navLinkHover: 'var(--color-orange-500)',
};

const DARK_THEME = {
  background: 'var(--color-black)',
  headerColor: 'var(--color-white)',
  copyColor: 'var(--color-gray-200)',
  linkColor: 'var(--color-blue-600)',
  highlightColor: 'var(--color-orange-400)',
  auxiliaryColor: 'var(--color-gray-600)',
  borderColor: 'var(--color-charcoal)',
  wrapperOverlay: 'rgba(255, 255, 255, 0.05)',
  cardColor: 'var(--color-gray-200)',
  cardOverlay: 'rgba(255, 255, 255, 0.1)',
  cardLinkColor: 'var(--color-blue-600)',
  cardHeaderColor: 'var(--color-orange-200)',
  cardInfoColor: 'var(--color-gray-200)',
  inputColor: 'var(--color-white)',
  inputCaretColor: 'var(--color-gray-400)',
  inputBorderColor: 'var(--color-gray-600)',
  inputLabelColor: 'var(--color-gray-200)',
  inputPlaceholderColor: 'rgba(255, 255, 255, 0.33)',
  inputPlaceholderHover: 'rgba(255, 255, 255, 0.66)',
  inputAutofillColor: 'var(--color-orange-400)',
  cvHeaderColor: 'var(--color-orange-400)',
  cvSubheaderColor: 'var(--color-orange-200)',
  cvInterfaceColor: 'var(--color-gray-600)',
  cvBorderColor: 'var(--color-orange-400)',
  blogSyntaxColor: 'var(--color-orange-400)',
  navLinkHover: 'var(--color-blue-500)',
};

export const THEMES = {
  light: LIGHT_THEME,
  dark: DARK_THEME,
};

export const DEFAULT_THEME = 'light';
